// The set of indexable pages under test, mirroring the country/page
// availability matrix and localized pathnames in `src/i18n/routing.ts` and
// CLAUDE.md. Kept as a plain literal (not imported from the app) so the test
// stays a black-box check of the rendered site and fails loudly if routing
// changes without the tests being updated.

export type TestPage = {
  /** URL path (always trailing-slashed, matching `trailingSlash: true`). */
  path: string;
  /** Expected `<html lang>` value. */
  lang: string;
  /** Human label for test titles. */
  label: string;
};

// Country landing pages — every locale.
const countryPages: TestPage[] = [
  { path: "/uk/", lang: "en", label: "country uk" },
  { path: "/de/", lang: "de", label: "country de" },
  { path: "/de/en/", lang: "en", label: "country de-EN" },
  { path: "/fr/", lang: "fr", label: "country fr" },
  { path: "/fr/en/", lang: "en", label: "country fr-EN" },
  { path: "/nl/", lang: "nl", label: "country nl" },
  { path: "/nl/en/", lang: "en", label: "country nl-EN" },
  { path: "/at/", lang: "de", label: "country at" },
  { path: "/at/en/", lang: "en", label: "country at-EN" },
  { path: "/be/", lang: "en", label: "country be" },
  { path: "/cz/", lang: "cs", label: "country cz" },
  { path: "/cz/en/", lang: "en", label: "country cz-EN" },
  { path: "/dk/", lang: "da", label: "country dk" },
  { path: "/gr/", lang: "el", label: "country gr" },
  { path: "/no/", lang: "nb", label: "country no" },
  { path: "/pl/", lang: "pl", label: "country pl" },
  { path: "/se/", lang: "sv", label: "country se" },
  { path: "/ee/", lang: "et", label: "country ee" },
  { path: "/ee/en/", lang: "en", label: "country ee-EN" },
  { path: "/fi/", lang: "fi", label: "country fi" },
  { path: "/fi/en/", lang: "en", label: "country fi-EN" },
  { path: "/es/", lang: "es", label: "country es" },
  { path: "/es/en/", lang: "en", label: "country es-EN" },
  { path: "/lv/", lang: "lv", label: "country lv" },
  { path: "/lv/en/", lang: "en", label: "country lv-EN" },
  { path: "/is/", lang: "is", label: "country is" },
  { path: "/is/en/", lang: "en", label: "country is-EN" },
  { path: "/pt/", lang: "pt", label: "country pt" },
  { path: "/pt/en/", lang: "en", label: "country pt-EN" },
  { path: "/hu/", lang: "hu", label: "country hu" },
  { path: "/hu/en/", lang: "en", label: "country hu-EN" },
  { path: "/si/", lang: "sl", label: "country si" },
  { path: "/si/en/", lang: "en", label: "country si-EN" },
  { path: "/lt/", lang: "lt", label: "country lt" },
  { path: "/lt/en/", lang: "en", label: "country lt-EN" },
  { path: "/rs/", lang: "sr", label: "country rs" },
  { path: "/rs/en/", lang: "en", label: "country rs-EN" },
  { path: "/ie/", lang: "en", label: "country ie" },
  { path: "/sk/", lang: "sk", label: "country sk" },
  { path: "/sk/en/", lang: "en", label: "country sk-EN" },
  { path: "/ba/", lang: "bs", label: "country ba" },
  { path: "/ba/en/", lang: "en", label: "country ba-EN" },
  { path: "/ch/", lang: "de", label: "country ch" },
  { path: "/ch/en/", lang: "en", label: "country ch-EN" },
  { path: "/al/", lang: "sq", label: "country al" },
  { path: "/al/en/", lang: "en", label: "country al-EN" },
  { path: "/mk/", lang: "mk", label: "country mk" },
  { path: "/mk/en/", lang: "en", label: "country mk-EN" },
  { path: "/ro/", lang: "ro", label: "country ro" },
  { path: "/ro/en/", lang: "en", label: "country ro-EN" },
  { path: "/cy/", lang: "el", label: "country cy" },
  { path: "/cy/en/", lang: "en", label: "country cy-EN" },
  { path: "/mt/", lang: "en", label: "country mt" },
  { path: "/md/", lang: "ro", label: "country md" },
  { path: "/md/en/", lang: "en", label: "country md-EN" },
  { path: "/it/", lang: "it", label: "country it" },
  { path: "/it/en/", lang: "en", label: "country it-EN" },
  { path: "/hr/", lang: "hr", label: "country hr" },
  { path: "/hr/en/", lang: "en", label: "country hr-EN" },
  { path: "/bg/", lang: "bg", label: "country bg" },
  { path: "/bg/en/", lang: "en", label: "country bg-EN" },
  { path: "/tr/", lang: "tr", label: "country tr" },
  { path: "/tr/en/", lang: "en", label: "country tr-EN" },
  { path: "/ge/", lang: "ka", label: "country ge" },
  { path: "/ge/en/", lang: "en", label: "country ge-EN" },
  { path: "/am/", lang: "hy", label: "country am" },
  { path: "/am/en/", lang: "en", label: "country am-EN" },
  { path: "/az/", lang: "az", label: "country az" },
  { path: "/az/en/", lang: "en", label: "country az-EN" },
  { path: "/ua/", lang: "uk", label: "country ua" },
  { path: "/ua/en/", lang: "en", label: "country ua-EN" },
  { path: "/uz/", lang: "uz", label: "country uz" },
  { path: "/uz/en/", lang: "en", label: "country uz-EN" },
  { path: "/by/", lang: "be", label: "country by" },
  { path: "/by/en/", lang: "en", label: "country by-EN" },
  { path: "/kz/", lang: "kk", label: "country kz" },
  { path: "/kz/en/", lang: "en", label: "country kz-EN" },
  { path: "/xk/", lang: "sq", label: "country xk" },
  { path: "/xk/en/", lang: "en", label: "country xk-EN" },
  { path: "/ru/", lang: "ru", label: "country ru" },
  { path: "/ru/en/", lang: "en", label: "country ru-EN" },
  { path: "/tj/", lang: "tg", label: "country tj" },
  { path: "/tj/en/", lang: "en", label: "country tj-EN" },
  { path: "/tm/", lang: "tk", label: "country tm" },
  { path: "/tm/en/", lang: "en", label: "country tm-EN" },
  { path: "/kg/", lang: "ky", label: "country kg" },
  { path: "/kg/en/", lang: "en", label: "country kg-EN" },
];

// Airport-list pages — localized slugs per locale.
const airportListPages: TestPage[] = [
  { path: "/uk/airport-list-uk/", lang: "en", label: "list uk" },
  { path: "/de/flughafen-liste-deutschland/", lang: "de", label: "list de" },
  { path: "/de/en/airport-list-germany/", lang: "en", label: "list de-EN" },
  { path: "/fr/liste-des-aeroports-francais/", lang: "fr", label: "list fr" },
  { path: "/fr/en/airport-list-france/", lang: "en", label: "list fr-EN" },
  { path: "/nl/luchthavenlijst-nederland/", lang: "nl", label: "list nl" },
  { path: "/nl/en/airport-list-netherlands/", lang: "en", label: "list nl-EN" },
  { path: "/at/flughafen-liste-oesterreich/", lang: "de", label: "list at" },
  { path: "/at/en/airport-list-austria/", lang: "en", label: "list at-EN" },
  { path: "/be/airport-list-belgium/", lang: "en", label: "list be" },
  { path: "/cz/letiste-cesko/", lang: "cs", label: "list cz" },
  { path: "/dk/flyvepladser-danmark/", lang: "da", label: "list dk" },
  { path: "/gr/aerolimenes-ellada/", lang: "el", label: "list gr" },
  { path: "/no/flyplasser-norge/", lang: "nb", label: "list no" },
  { path: "/pl/lotniska-polska/", lang: "pl", label: "list pl" },
  { path: "/se/flygplatser-sverige/", lang: "sv", label: "list se" },
  { path: "/ee/lennuvaljade-nimekiri-eesti/", lang: "et", label: "list ee" },
  { path: "/ee/en/airport-list-estonia/", lang: "en", label: "list ee-EN" },
  { path: "/fi/lentopaikat-suomi/", lang: "fi", label: "list fi" },
  { path: "/fi/en/airport-list-finland/", lang: "en", label: "list fi-EN" },
  { path: "/es/lista-de-aeropuertos-espana/", lang: "es", label: "list es" },
  { path: "/es/en/airport-list-spain/", lang: "en", label: "list es-EN" },
  { path: "/lv/lidlauku-saraksts-latvija/", lang: "lv", label: "list lv" },
  { path: "/lv/en/airport-list-latvia/", lang: "en", label: "list lv-EN" },
  { path: "/is/flugvallalisti-island/", lang: "is", label: "list is" },
  { path: "/is/en/airport-list-iceland/", lang: "en", label: "list is-EN" },
  { path: "/pt/lista-de-aerodromos-portugal/", lang: "pt", label: "list pt" },
  { path: "/pt/en/airport-list-portugal/", lang: "en", label: "list pt-EN" },
  {
    path: "/hu/repuloterek-listaja-magyarorszag/",
    lang: "hu",
    label: "list hu",
  },
  { path: "/hu/en/airport-list-hungary/", lang: "en", label: "list hu-EN" },
  { path: "/si/seznam-letalisc-slovenija/", lang: "sl", label: "list si" },
  { path: "/si/en/airport-list-slovenia/", lang: "en", label: "list si-EN" },
  { path: "/lt/oro-uostu-sarasas-lietuva/", lang: "lt", label: "list lt" },
  { path: "/lt/en/airport-list-lithuania/", lang: "en", label: "list lt-EN" },
  { path: "/rs/lista-aerodroma-srbija/", lang: "sr", label: "list rs" },
  { path: "/rs/en/airport-list-serbia/", lang: "en", label: "list rs-EN" },
  { path: "/ie/airport-list-ireland/", lang: "en", label: "list ie" },
  { path: "/sk/letiska-slovensko/", lang: "sk", label: "list sk" },
  { path: "/sk/en/airport-list-slovakia/", lang: "en", label: "list sk-EN" },
  { path: "/ba/lista-aerodroma-bih/", lang: "bs", label: "list ba" },
  { path: "/ba/en/airport-list-bosnia/", lang: "en", label: "list ba-EN" },
  { path: "/ch/flugplaetze-schweiz/", lang: "de", label: "list ch" },
  { path: "/ch/en/airport-list-switzerland/", lang: "en", label: "list ch-EN" },
  { path: "/al/aeroportet-shqiperi/", lang: "sq", label: "list al" },
  { path: "/al/en/airport-list-albania/", lang: "en", label: "list al-EN" },
  { path: "/mk/aerodromi-severna-makedonija/", lang: "mk", label: "list mk" },
  {
    path: "/mk/en/airport-list-north-macedonia/",
    lang: "en",
    label: "list mk-EN",
  },
  { path: "/ro/lista-aeroporturi-romania/", lang: "ro", label: "list ro" },
  { path: "/ro/en/airport-list-romania/", lang: "en", label: "list ro-EN" },
  { path: "/cy/aerolimenes-kypros/", lang: "el", label: "list cy" },
  { path: "/cy/en/airport-list-cyprus/", lang: "en", label: "list cy-EN" },
  { path: "/mt/airport-list-malta/", lang: "en", label: "list mt" },
  { path: "/md/lista-aeroporturi-moldova/", lang: "ro", label: "list md" },
  { path: "/md/en/airport-list-moldova/", lang: "en", label: "list md-EN" },
  { path: "/it/elenco-aeroporti-italia/", lang: "it", label: "list it" },
  { path: "/it/en/airport-list-italy/", lang: "en", label: "list it-EN" },
  { path: "/hr/popis-zracnih-luka-hrvatska/", lang: "hr", label: "list hr" },
  { path: "/hr/en/airport-list-croatia/", lang: "en", label: "list hr-EN" },
  { path: "/bg/letishta-balgariya/", lang: "bg", label: "list bg" },
  { path: "/bg/en/airport-list-bulgaria/", lang: "en", label: "list bg-EN" },
  { path: "/tr/havalimanlari-turkiye/", lang: "tr", label: "list tr" },
  { path: "/tr/en/airport-list-turkey/", lang: "en", label: "list tr-EN" },
  { path: "/ge/aeroportebi-sakartvelo/", lang: "ka", label: "list ge" },
  { path: "/ge/en/airport-list-georgia/", lang: "en", label: "list ge-EN" },
  { path: "/am/odanavakayanner-hayastan/", lang: "hy", label: "list am" },
  { path: "/am/en/airport-list-armenia/", lang: "en", label: "list am-EN" },
  { path: "/az/hava-limanlari-azerbaycan/", lang: "az", label: "list az" },
  { path: "/az/en/airport-list-azerbaijan/", lang: "en", label: "list az-EN" },
  { path: "/ua/perelik-aeroportiv-ukrayina/", lang: "uk", label: "list ua" },
  { path: "/ua/en/airport-list-ukraine/", lang: "en", label: "list ua-EN" },
  { path: "/uz/aeroportlar-royxati-ozbekiston/", lang: "uz", label: "list uz" },
  { path: "/uz/en/airport-list-uzbekistan/", lang: "en", label: "list uz-EN" },
  { path: "/by/pieralik-aeraportau-bielarus/", lang: "be", label: "list by" },
  { path: "/by/en/airport-list-belarus/", lang: "en", label: "list by-EN" },
  { path: "/kz/aeroportar-tizimi-qazaqstan/", lang: "kk", label: "list kz" },
  { path: "/kz/en/airport-list-kazakhstan/", lang: "en", label: "list kz-EN" },
  { path: "/xk/lista-e-aeroporteve-kosove/", lang: "sq", label: "list xk" },
  { path: "/xk/en/airport-list-kosovo/", lang: "en", label: "list xk-EN" },
  { path: "/ru/spisok-aeroportov-rossiya/", lang: "ru", label: "list ru" },
  { path: "/ru/en/airport-list-russia/", lang: "en", label: "list ru-EN" },
  { path: "/tj/ruyxati-furudgohhoi-tojikiston/", lang: "tg", label: "list tj" },
  { path: "/tj/en/airport-list-tajikistan/", lang: "en", label: "list tj-EN" },
  { path: "/tm/turkmenistan-howa-menzilleri/", lang: "tk", label: "list tm" },
  {
    path: "/tm/en/airport-list-turkmenistan/",
    lang: "en",
    label: "list tm-EN",
  },
  { path: "/kg/kyrgyzstan-aeroporttor-tizmesi/", lang: "ky", label: "list kg" },
  { path: "/kg/en/airport-list-kyrgyzstan/", lang: "en", label: "list kg-EN" },
];

// Search pages — only where the type is available for the country.
const searchPages: TestPage[] = [
  // VFR: everywhere except France
  { path: "/uk/vfr/", lang: "en", label: "vfr uk" },
  { path: "/de/vfr/", lang: "de", label: "vfr de" },
  { path: "/nl/vfr/", lang: "nl", label: "vfr nl" },
  { path: "/at/vfr/", lang: "de", label: "vfr at" },
  // IFR: Germany only
  { path: "/de/ifr/", lang: "de", label: "ifr de" },
  { path: "/de/en/ifr/", lang: "en", label: "ifr de-EN" },
  // Heliports: everywhere except France
  { path: "/uk/heliports/", lang: "en", label: "heliports uk" },
  { path: "/de/heliports/", lang: "de", label: "heliports de" },
  { path: "/nl/heliports/", lang: "nl", label: "heliports nl" },
  { path: "/at/heliports/", lang: "de", label: "heliports at" },
  // Military + Aeroports: France only
  { path: "/fr/military/", lang: "fr", label: "military fr" },
  { path: "/fr/en/military/", lang: "en", label: "military fr-EN" },
  { path: "/fr/aeroports/", lang: "fr", label: "aeroports fr" },
  { path: "/fr/en/aeroports/", lang: "en", label: "aeroports fr-EN" },
  // Belgium/Luxembourg (vfr, ifr, heliports, military)
  { path: "/be/vfr/", lang: "en", label: "vfr be" },
  { path: "/cz/vfr/", lang: "cs", label: "vfr cz" },
  { path: "/cz/en/vfr/", lang: "en", label: "vfr cz-EN" },
  { path: "/be/ifr/", lang: "en", label: "ifr be" },
  { path: "/be/heliports/", lang: "en", label: "heliports be" },
  { path: "/be/military/", lang: "en", label: "military be" },
  // Czechia (vfr from the VFR Manual + ifr from the eAIP; vfr rows above)
  { path: "/cz/ifr/", lang: "cs", label: "ifr cz" },
  // vfr + heliports countries (sample)
  { path: "/dk/vfr/", lang: "da", label: "vfr dk" },
  { path: "/gr/heliports/", lang: "el", label: "heliports gr" },
  { path: "/no/vfr/", lang: "nb", label: "vfr no" },
  { path: "/pl/vfr/", lang: "pl", label: "vfr pl" },
  { path: "/se/vfr/", lang: "sv", label: "vfr se" },
  { path: "/ee/vfr/", lang: "et", label: "vfr ee" },
  { path: "/ee/en/heliports/", lang: "en", label: "heliports ee-EN" },
  { path: "/fi/vfr/", lang: "fi", label: "vfr fi" },
  { path: "/fi/en/heliports/", lang: "en", label: "heliports fi-EN" },
  { path: "/es/vfr/", lang: "es", label: "vfr es" },
  { path: "/es/en/vfr/", lang: "en", label: "vfr es-EN" },
  { path: "/lv/vfr/", lang: "lv", label: "vfr lv" },
  { path: "/lv/en/heliports/", lang: "en", label: "heliports lv-EN" },
  { path: "/is/vfr/", lang: "is", label: "vfr is" },
  { path: "/is/en/vfr/", lang: "en", label: "vfr is-EN" },
  { path: "/pt/vfr/", lang: "pt", label: "vfr pt" },
  { path: "/pt/en/vfr/", lang: "en", label: "vfr pt-EN" },
  { path: "/hu/vfr/", lang: "hu", label: "vfr hu" },
  { path: "/hu/en/vfr/", lang: "en", label: "vfr hu-EN" },
  { path: "/si/vfr/", lang: "sl", label: "vfr si" },
  { path: "/si/en/vfr/", lang: "en", label: "vfr si-EN" },
  { path: "/lt/vfr/", lang: "lt", label: "vfr lt" },
  { path: "/lt/en/vfr/", lang: "en", label: "vfr lt-EN" },
  { path: "/rs/vfr/", lang: "sr", label: "vfr rs" },
  { path: "/rs/en/vfr/", lang: "en", label: "vfr rs-EN" },
  { path: "/ie/vfr/", lang: "en", label: "vfr ie" },
  { path: "/sk/vfr/", lang: "sk", label: "vfr sk" },
  { path: "/sk/en/vfr/", lang: "en", label: "vfr sk-EN" },
  { path: "/ba/vfr/", lang: "bs", label: "vfr ba" },
  { path: "/ba/en/vfr/", lang: "en", label: "vfr ba-EN" },
  { path: "/ch/vfr/", lang: "de", label: "vfr ch" },
  { path: "/ch/en/vfr/", lang: "en", label: "vfr ch-EN" },
  { path: "/al/vfr/", lang: "sq", label: "vfr al" },
  { path: "/al/en/vfr/", lang: "en", label: "vfr al-EN" },
  { path: "/mk/vfr/", lang: "mk", label: "vfr mk" },
  { path: "/mk/en/vfr/", lang: "en", label: "vfr mk-EN" },
  { path: "/ro/vfr/", lang: "ro", label: "vfr ro" },
  { path: "/ro/en/vfr/", lang: "en", label: "vfr ro-EN" },
  { path: "/cy/vfr/", lang: "el", label: "vfr cy" },
  { path: "/cy/en/vfr/", lang: "en", label: "vfr cy-EN" },
  { path: "/mt/vfr/", lang: "en", label: "vfr mt" },
  { path: "/md/vfr/", lang: "ro", label: "vfr md" },
  { path: "/md/en/vfr/", lang: "en", label: "vfr md-EN" },
  { path: "/it/vfr/", lang: "it", label: "vfr it" },
  { path: "/it/en/vfr/", lang: "en", label: "vfr it-EN" },
  { path: "/hr/vfr/", lang: "hr", label: "vfr hr" },
  { path: "/hr/en/vfr/", lang: "en", label: "vfr hr-EN" },
  { path: "/bg/vfr/", lang: "bg", label: "vfr bg" },
  { path: "/bg/en/vfr/", lang: "en", label: "vfr bg-EN" },
  { path: "/tr/vfr/", lang: "tr", label: "vfr tr" },
  { path: "/tr/en/vfr/", lang: "en", label: "vfr tr-EN" },
  { path: "/ge/vfr/", lang: "ka", label: "vfr ge" },
  { path: "/ge/en/vfr/", lang: "en", label: "vfr ge-EN" },
  { path: "/am/vfr/", lang: "hy", label: "vfr am" },
  { path: "/am/en/vfr/", lang: "en", label: "vfr am-EN" },
  { path: "/az/vfr/", lang: "az", label: "vfr az" },
  { path: "/az/en/vfr/", lang: "en", label: "vfr az-EN" },
  { path: "/ua/vfr/", lang: "uk", label: "vfr ua" },
  { path: "/ua/en/vfr/", lang: "en", label: "vfr ua-EN" },
  { path: "/uz/vfr/", lang: "uz", label: "vfr uz" },
  { path: "/uz/en/vfr/", lang: "en", label: "vfr uz-EN" },
  { path: "/by/vfr/", lang: "be", label: "vfr by" },
  { path: "/by/en/vfr/", lang: "en", label: "vfr by-EN" },
  { path: "/kz/vfr/", lang: "kk", label: "vfr kz" },
  { path: "/kz/en/vfr/", lang: "en", label: "vfr kz-EN" },
  { path: "/xk/vfr/", lang: "sq", label: "vfr xk" },
  { path: "/xk/en/vfr/", lang: "en", label: "vfr xk-EN" },
  { path: "/ru/vfr/", lang: "ru", label: "vfr ru" },
  { path: "/ru/en/vfr/", lang: "en", label: "vfr ru-EN" },
  { path: "/tj/vfr/", lang: "tg", label: "vfr tj" },
  { path: "/tj/en/vfr/", lang: "en", label: "vfr tj-EN" },
  { path: "/tm/vfr/", lang: "tk", label: "vfr tm" },
  { path: "/tm/en/vfr/", lang: "en", label: "vfr tm-EN" },
  { path: "/kg/vfr/", lang: "ky", label: "vfr kg" },
  { path: "/kg/en/vfr/", lang: "en", label: "vfr kg-EN" },
];

// Legal pages - single-language, paired by topic and cross-linked with
// hreflang. English at the root (/terms /imprint /privacy); German served under
// /de/ (/de/agb /de/impressum /de/datenschutz - the root routes rewritten by
// middleware, so the bare /agb etc. 301 to /de/...). Old `/<locale>/terms` URLs
// 301-redirect to /terms (middleware.ts).
const legalPages: TestPage[] = [
  { path: "/terms/", lang: "en", label: "terms" },
  { path: "/imprint/", lang: "en", label: "imprint" },
  { path: "/privacy/", lang: "en", label: "privacy" },
  { path: "/de/agb/", lang: "de", label: "agb" },
  { path: "/de/impressum/", lang: "de", label: "impressum" },
  { path: "/de/datenschutz/", lang: "de", label: "datenschutz" },
];

// EFB guide pages - every locale (single uniform slug /efb).
const efbPages: TestPage[] = [
  { path: "/uk/efb/", lang: "en", label: "efb uk" },
  { path: "/de/efb/", lang: "de", label: "efb de" },
  { path: "/de/en/efb/", lang: "en", label: "efb de-EN" },
  { path: "/fr/efb/", lang: "fr", label: "efb fr" },
  { path: "/fr/en/efb/", lang: "en", label: "efb fr-EN" },
  { path: "/nl/efb/", lang: "nl", label: "efb nl" },
  { path: "/nl/en/efb/", lang: "en", label: "efb nl-EN" },
  { path: "/at/efb/", lang: "de", label: "efb at" },
  { path: "/at/en/efb/", lang: "en", label: "efb at-EN" },
  { path: "/be/efb/", lang: "en", label: "efb be" },
  { path: "/cz/efb/", lang: "cs", label: "efb cz" },
  { path: "/cz/en/efb/", lang: "en", label: "efb cz-EN" },
  { path: "/dk/efb/", lang: "da", label: "efb dk" },
  { path: "/dk/en/efb/", lang: "en", label: "efb dk-EN" },
  { path: "/gr/efb/", lang: "el", label: "efb gr" },
  { path: "/gr/en/efb/", lang: "en", label: "efb gr-EN" },
  { path: "/no/efb/", lang: "nb", label: "efb no" },
  { path: "/no/en/efb/", lang: "en", label: "efb no-EN" },
  { path: "/pl/efb/", lang: "pl", label: "efb pl" },
  { path: "/pl/en/efb/", lang: "en", label: "efb pl-EN" },
  { path: "/se/efb/", lang: "sv", label: "efb se" },
  { path: "/se/en/efb/", lang: "en", label: "efb se-EN" },
  { path: "/ee/efb/", lang: "et", label: "efb ee" },
  { path: "/ee/en/efb/", lang: "en", label: "efb ee-EN" },
  { path: "/fi/efb/", lang: "fi", label: "efb fi" },
  { path: "/fi/en/efb/", lang: "en", label: "efb fi-EN" },
  { path: "/es/efb/", lang: "es", label: "efb es" },
  { path: "/es/en/efb/", lang: "en", label: "efb es-EN" },
  { path: "/lv/efb/", lang: "lv", label: "efb lv" },
  { path: "/lv/en/efb/", lang: "en", label: "efb lv-EN" },
  { path: "/is/efb/", lang: "is", label: "efb is" },
  { path: "/is/en/efb/", lang: "en", label: "efb is-EN" },
  { path: "/pt/efb/", lang: "pt", label: "efb pt" },
  { path: "/pt/en/efb/", lang: "en", label: "efb pt-EN" },
  { path: "/hu/efb/", lang: "hu", label: "efb hu" },
  { path: "/hu/en/efb/", lang: "en", label: "efb hu-EN" },
  { path: "/si/efb/", lang: "sl", label: "efb si" },
  { path: "/si/en/efb/", lang: "en", label: "efb si-EN" },
  { path: "/lt/efb/", lang: "lt", label: "efb lt" },
  { path: "/lt/en/efb/", lang: "en", label: "efb lt-EN" },
  { path: "/rs/efb/", lang: "sr", label: "efb rs" },
  { path: "/rs/en/efb/", lang: "en", label: "efb rs-EN" },
  { path: "/ie/efb/", lang: "en", label: "efb ie" },
  { path: "/sk/efb/", lang: "sk", label: "efb sk" },
  { path: "/sk/en/efb/", lang: "en", label: "efb sk-EN" },
  { path: "/ba/efb/", lang: "bs", label: "efb ba" },
  { path: "/ba/en/efb/", lang: "en", label: "efb ba-EN" },
  { path: "/ch/efb/", lang: "de", label: "efb ch" },
  { path: "/ch/en/efb/", lang: "en", label: "efb ch-EN" },
  { path: "/al/efb/", lang: "sq", label: "efb al" },
  { path: "/al/en/efb/", lang: "en", label: "efb al-EN" },
];

/** Root landing page (`/`) — its own <html> with a manually rendered <head>. */
export const rootPage: TestPage = { path: "/", lang: "en", label: "root" };

/** Every indexable page whose metadata must be unique and complete. */
export const allPages: TestPage[] = [
  rootPage,
  ...countryPages,
  ...airportListPages,
  ...searchPages,
  ...legalPages,
  ...efbPages,
];

/** A representative subset for the (slower) accessibility sweep. */
export const a11yPages: TestPage[] = [
  rootPage,
  { path: "/de/", lang: "de", label: "country de" },
  // A prefix != ISO-code country (at -> de): catches invalid [lang] values
  // derived from the URL prefix, which de/fr mask (Lighthouse hit on /at/).
  { path: "/at/", lang: "de", label: "country at" },
  { path: "/de/flughafen-liste-deutschland/", lang: "de", label: "list de" },
  { path: "/de/vfr/", lang: "de", label: "vfr de" },
  { path: "/fr/military/", lang: "fr", label: "military fr" },
  { path: "/de/efb/", lang: "de", label: "efb de" },
];
