// The set of indexable pages under test, mirroring the country/page
// availability matrix and localized pathnames in `src/i18n/routing.ts` and
// CLAUDE.md. Kept as a plain literal (not imported from the app) so the test
// stays a black-box check of the rendered site and fails loudly if routing
// changes without the tests being updated.

export type TestPage = {
  /** URL path (always trailing-slashed, matching `trailingSlash: true`). */
  path: string;
  /** Expected `<html lang>` value. */
  lang: string;
  /** Human label for test titles. */
  label: string;
};

// Country landing pages — every locale.
const countryPages: TestPage[] = [
  { path: "/uk/", lang: "en", label: "country uk" },
  { path: "/de/", lang: "de", label: "country de" },
  { path: "/de/en/", lang: "en", label: "country de-EN" },
  { path: "/fr/", lang: "fr", label: "country fr" },
  { path: "/fr/en/", lang: "en", label: "country fr-EN" },
  { path: "/nl/", lang: "nl", label: "country nl" },
  { path: "/nl/en/", lang: "en", label: "country nl-EN" },
  { path: "/at/", lang: "de", label: "country at" },
  { path: "/at/en/", lang: "en", label: "country at-EN" },
  { path: "/be/", lang: "en", label: "country be" },
  { path: "/cz/", lang: "cs", label: "country cz" },
  { path: "/cz/en/", lang: "en", label: "country cz-EN" },
  { path: "/dk/", lang: "da", label: "country dk" },
  { path: "/gr/", lang: "el", label: "country gr" },
  { path: "/no/", lang: "nb", label: "country no" },
  { path: "/pl/", lang: "pl", label: "country pl" },
  { path: "/se/", lang: "sv", label: "country se" },
  { path: "/ee/", lang: "et", label: "country ee" },
  { path: "/ee/en/", lang: "en", label: "country ee-EN" },
  { path: "/fi/", lang: "fi", label: "country fi" },
  { path: "/fi/en/", lang: "en", label: "country fi-EN" },
  { path: "/es/", lang: "es", label: "country es" },
  { path: "/es/en/", lang: "en", label: "country es-EN" },
  { path: "/lv/", lang: "lv", label: "country lv" },
  { path: "/lv/en/", lang: "en", label: "country lv-EN" },
  { path: "/is/", lang: "is", label: "country is" },
  { path: "/is/en/", lang: "en", label: "country is-EN" },
  { path: "/pt/", lang: "pt", label: "country pt" },
  { path: "/pt/en/", lang: "en", label: "country pt-EN" },
  { path: "/hu/", lang: "hu", label: "country hu" },
  { path: "/hu/en/", lang: "en", label: "country hu-EN" },
  { path: "/si/", lang: "sl", label: "country si" },
  { path: "/si/en/", lang: "en", label: "country si-EN" },
  { path: "/lt/", lang: "lt", label: "country lt" },
  { path: "/lt/en/", lang: "en", label: "country lt-EN" },
  { path: "/rs/", lang: "sr", label: "country rs" },
  { path: "/rs/en/", lang: "en", label: "country rs-EN" },
  { path: "/ie/", lang: "en", label: "country ie" },
  { path: "/sk/", lang: "sk", label: "country sk" },
  { path: "/sk/en/", lang: "en", label: "country sk-EN" },
  { path: "/ba/", lang: "bs", label: "country ba" },
  { path: "/ba/en/", lang: "en", label: "country ba-EN" },
  { path: "/ch/", lang: "de", label: "country ch" },
  { path: "/ch/en/", lang: "en", label: "country ch-EN" },
  { path: "/al/", lang: "sq", label: "country al" },
  { path: "/al/en/", lang: "en", label: "country al-EN" },
  { path: "/mk/", lang: "mk", label: "country mk" },
  { path: "/mk/en/", lang: "en", label: "country mk-EN" },
  { path: "/ro/", lang: "ro", label: "country ro" },
  { path: "/ro/en/", lang: "en", label: "country ro-EN" },
  { path: "/cy/", lang: "el", label: "country cy" },
  { path: "/cy/en/", lang: "en", label: "country cy-EN" },
  { path: "/mt/", lang: "en", label: "country mt" },
  { path: "/md/", lang: "ro", label: "country md" },
  { path: "/md/en/", lang: "en", label: "country md-EN" },
];

// Airport-list pages — localized slugs per locale.
const airportListPages: TestPage[] = [
  { path: "/uk/airport-list-uk/", lang: "en", label: "list uk" },
  { path: "/de/flughafen-liste-deutschland/", lang: "de", label: "list de" },
  { path: "/de/en/airport-list-germany/", lang: "en", label: "list de-EN" },
  { path: "/fr/liste-des-aeroports-francais/", lang: "fr", label: "list fr" },
  { path: "/fr/en/airport-list-france/", lang: "en", label: "list fr-EN" },
  { path: "/nl/luchthavenlijst-nederland/", lang: "nl", label: "list nl" },
  { path: "/nl/en/airport-list-netherlands/", lang: "en", label: "list nl-EN" },
  { path: "/at/flughafen-liste-oesterreich/", lang: "de", label: "list at" },
  { path: "/at/en/airport-list-austria/", lang: "en", label: "list at-EN" },
  { path: "/be/airport-list-belgium/", lang: "en", label: "list be" },
  { path: "/cz/letiste-cesko/", lang: "cs", label: "list cz" },
  { path: "/dk/flyvepladser-danmark/", lang: "da", label: "list dk" },
  { path: "/gr/aerolimenes-ellada/", lang: "el", label: "list gr" },
  { path: "/no/flyplasser-norge/", lang: "nb", label: "list no" },
  { path: "/pl/lotniska-polska/", lang: "pl", label: "list pl" },
  { path: "/se/flygplatser-sverige/", lang: "sv", label: "list se" },
  { path: "/ee/lennuvaljade-nimekiri-eesti/", lang: "et", label: "list ee" },
  { path: "/ee/en/airport-list-estonia/", lang: "en", label: "list ee-EN" },
  { path: "/fi/lentopaikat-suomi/", lang: "fi", label: "list fi" },
  { path: "/fi/en/airport-list-finland/", lang: "en", label: "list fi-EN" },
  { path: "/es/lista-de-aeropuertos-espana/", lang: "es", label: "list es" },
  { path: "/es/en/airport-list-spain/", lang: "en", label: "list es-EN" },
  { path: "/lv/lidlauku-saraksts-latvija/", lang: "lv", label: "list lv" },
  { path: "/lv/en/airport-list-latvia/", lang: "en", label: "list lv-EN" },
  { path: "/is/flugvallalisti-island/", lang: "is", label: "list is" },
  { path: "/is/en/airport-list-iceland/", lang: "en", label: "list is-EN" },
  { path: "/pt/lista-de-aerodromos-portugal/", lang: "pt", label: "list pt" },
  { path: "/pt/en/airport-list-portugal/", lang: "en", label: "list pt-EN" },
  {
    path: "/hu/repuloterek-listaja-magyarorszag/",
    lang: "hu",
    label: "list hu",
  },
  { path: "/hu/en/airport-list-hungary/", lang: "en", label: "list hu-EN" },
  { path: "/si/seznam-letalisc-slovenija/", lang: "sl", label: "list si" },
  { path: "/si/en/airport-list-slovenia/", lang: "en", label: "list si-EN" },
  { path: "/lt/oro-uostu-sarasas-lietuva/", lang: "lt", label: "list lt" },
  { path: "/lt/en/airport-list-lithuania/", lang: "en", label: "list lt-EN" },
  { path: "/rs/lista-aerodroma-srbija/", lang: "sr", label: "list rs" },
  { path: "/rs/en/airport-list-serbia/", lang: "en", label: "list rs-EN" },
  { path: "/ie/airport-list-ireland/", lang: "en", label: "list ie" },
  { path: "/sk/letiska-slovensko/", lang: "sk", label: "list sk" },
  { path: "/sk/en/airport-list-slovakia/", lang: "en", label: "list sk-EN" },
  { path: "/ba/lista-aerodroma-bih/", lang: "bs", label: "list ba" },
  { path: "/ba/en/airport-list-bosnia/", lang: "en", label: "list ba-EN" },
  { path: "/ch/flugplaetze-schweiz/", lang: "de", label: "list ch" },
  { path: "/ch/en/airport-list-switzerland/", lang: "en", label: "list ch-EN" },
  { path: "/al/aeroportet-shqiperi/", lang: "sq", label: "list al" },
  { path: "/al/en/airport-list-albania/", lang: "en", label: "list al-EN" },
  { path: "/mk/aerodromi-severna-makedonija/", lang: "mk", label: "list mk" },
  {
    path: "/mk/en/airport-list-north-macedonia/",
    lang: "en",
    label: "list mk-EN",
  },
  { path: "/ro/lista-aeroporturi-romania/", lang: "ro", label: "list ro" },
  { path: "/ro/en/airport-list-romania/", lang: "en", label: "list ro-EN" },
  { path: "/cy/aerolimenes-kypros/", lang: "el", label: "list cy" },
  { path: "/cy/en/airport-list-cyprus/", lang: "en", label: "list cy-EN" },
  { path: "/mt/airport-list-malta/", lang: "en", label: "list mt" },
  { path: "/md/lista-aeroporturi-moldova/", lang: "ro", label: "list md" },
  { path: "/md/en/airport-list-moldova/", lang: "en", label: "list md-EN" },
];

// Search pages — only where the type is available for the country.
const searchPages: TestPage[] = [
  // VFR: everywhere except France
  { path: "/uk/vfr/", lang: "en", label: "vfr uk" },
  { path: "/de/vfr/", lang: "de", label: "vfr de" },
  { path: "/nl/vfr/", lang: "nl", label: "vfr nl" },
  { path: "/at/vfr/", lang: "de", label: "vfr at" },
  // IFR: Germany only
  { path: "/de/ifr/", lang: "de", label: "ifr de" },
  { path: "/de/en/ifr/", lang: "en", label: "ifr de-EN" },
  // Heliports: everywhere except France
  { path: "/uk/heliports/", lang: "en", label: "heliports uk" },
  { path: "/de/heliports/", lang: "de", label: "heliports de" },
  { path: "/nl/heliports/", lang: "nl", label: "heliports nl" },
  { path: "/at/heliports/", lang: "de", label: "heliports at" },
  // Military + Aeroports: France only
  { path: "/fr/military/", lang: "fr", label: "military fr" },
  { path: "/fr/en/military/", lang: "en", label: "military fr-EN" },
  { path: "/fr/aeroports/", lang: "fr", label: "aeroports fr" },
  { path: "/fr/en/aeroports/", lang: "en", label: "aeroports fr-EN" },
  // Belgium/Luxembourg (vfr, ifr, heliports, military)
  { path: "/be/vfr/", lang: "en", label: "vfr be" },
  { path: "/cz/vfr/", lang: "cs", label: "vfr cz" },
  { path: "/cz/en/vfr/", lang: "en", label: "vfr cz-EN" },
  { path: "/be/ifr/", lang: "en", label: "ifr be" },
  { path: "/be/heliports/", lang: "en", label: "heliports be" },
  { path: "/be/military/", lang: "en", label: "military be" },
  // Czechia (vfr from the VFR Manual + ifr from the eAIP; vfr rows above)
  { path: "/cz/ifr/", lang: "cs", label: "ifr cz" },
  // vfr + heliports countries (sample)
  { path: "/dk/vfr/", lang: "da", label: "vfr dk" },
  { path: "/gr/heliports/", lang: "el", label: "heliports gr" },
  { path: "/no/vfr/", lang: "nb", label: "vfr no" },
  { path: "/pl/vfr/", lang: "pl", label: "vfr pl" },
  { path: "/se/vfr/", lang: "sv", label: "vfr se" },
  { path: "/ee/vfr/", lang: "et", label: "vfr ee" },
  { path: "/ee/en/heliports/", lang: "en", label: "heliports ee-EN" },
  { path: "/fi/vfr/", lang: "fi", label: "vfr fi" },
  { path: "/fi/en/heliports/", lang: "en", label: "heliports fi-EN" },
  { path: "/es/vfr/", lang: "es", label: "vfr es" },
  { path: "/es/en/vfr/", lang: "en", label: "vfr es-EN" },
  { path: "/lv/vfr/", lang: "lv", label: "vfr lv" },
  { path: "/lv/en/heliports/", lang: "en", label: "heliports lv-EN" },
  { path: "/is/vfr/", lang: "is", label: "vfr is" },
  { path: "/is/en/vfr/", lang: "en", label: "vfr is-EN" },
  { path: "/pt/vfr/", lang: "pt", label: "vfr pt" },
  { path: "/pt/en/vfr/", lang: "en", label: "vfr pt-EN" },
  { path: "/hu/vfr/", lang: "hu", label: "vfr hu" },
  { path: "/hu/en/vfr/", lang: "en", label: "vfr hu-EN" },
  { path: "/si/vfr/", lang: "sl", label: "vfr si" },
  { path: "/si/en/vfr/", lang: "en", label: "vfr si-EN" },
  { path: "/lt/vfr/", lang: "lt", label: "vfr lt" },
  { path: "/lt/en/vfr/", lang: "en", label: "vfr lt-EN" },
  { path: "/rs/vfr/", lang: "sr", label: "vfr rs" },
  { path: "/rs/en/vfr/", lang: "en", label: "vfr rs-EN" },
  { path: "/ie/vfr/", lang: "en", label: "vfr ie" },
  { path: "/sk/vfr/", lang: "sk", label: "vfr sk" },
  { path: "/sk/en/vfr/", lang: "en", label: "vfr sk-EN" },
  { path: "/ba/vfr/", lang: "bs", label: "vfr ba" },
  { path: "/ba/en/vfr/", lang: "en", label: "vfr ba-EN" },
  { path: "/ch/vfr/", lang: "de", label: "vfr ch" },
  { path: "/ch/en/vfr/", lang: "en", label: "vfr ch-EN" },
  { path: "/al/vfr/", lang: "sq", label: "vfr al" },
  { path: "/al/en/vfr/", lang: "en", label: "vfr al-EN" },
  { path: "/mk/vfr/", lang: "mk", label: "vfr mk" },
  { path: "/mk/en/vfr/", lang: "en", label: "vfr mk-EN" },
  { path: "/ro/vfr/", lang: "ro", label: "vfr ro" },
  { path: "/ro/en/vfr/", lang: "en", label: "vfr ro-EN" },
  { path: "/cy/vfr/", lang: "el", label: "vfr cy" },
  { path: "/cy/en/vfr/", lang: "en", label: "vfr cy-EN" },
  { path: "/mt/vfr/", lang: "en", label: "vfr mt" },
  { path: "/md/vfr/", lang: "ro", label: "vfr md" },
  { path: "/md/en/vfr/", lang: "en", label: "vfr md-EN" },
];

// Terms-of-service pages - every locale (single uniform slug /terms).
const termsPages: TestPage[] = [
  { path: "/uk/terms/", lang: "en", label: "terms uk" },
  { path: "/de/terms/", lang: "de", label: "terms de" },
  { path: "/de/en/terms/", lang: "en", label: "terms de-EN" },
  { path: "/fr/terms/", lang: "fr", label: "terms fr" },
  { path: "/fr/en/terms/", lang: "en", label: "terms fr-EN" },
  { path: "/nl/terms/", lang: "nl", label: "terms nl" },
  { path: "/nl/en/terms/", lang: "en", label: "terms nl-EN" },
  { path: "/at/terms/", lang: "de", label: "terms at" },
  { path: "/at/en/terms/", lang: "en", label: "terms at-EN" },
  { path: "/be/terms/", lang: "en", label: "terms be" },
  { path: "/cz/terms/", lang: "cs", label: "terms cz" },
  { path: "/cz/en/terms/", lang: "en", label: "terms cz-EN" },
  { path: "/dk/terms/", lang: "da", label: "terms dk" },
  { path: "/dk/en/terms/", lang: "en", label: "terms dk-EN" },
  { path: "/gr/terms/", lang: "el", label: "terms gr" },
  { path: "/gr/en/terms/", lang: "en", label: "terms gr-EN" },
  { path: "/no/terms/", lang: "nb", label: "terms no" },
  { path: "/no/en/terms/", lang: "en", label: "terms no-EN" },
  { path: "/pl/terms/", lang: "pl", label: "terms pl" },
  { path: "/pl/en/terms/", lang: "en", label: "terms pl-EN" },
  { path: "/se/terms/", lang: "sv", label: "terms se" },
  { path: "/se/en/terms/", lang: "en", label: "terms se-EN" },
  { path: "/ee/terms/", lang: "et", label: "terms ee" },
  { path: "/ee/en/terms/", lang: "en", label: "terms ee-EN" },
  { path: "/fi/terms/", lang: "fi", label: "terms fi" },
  { path: "/fi/en/terms/", lang: "en", label: "terms fi-EN" },
  { path: "/es/terms/", lang: "es", label: "terms es" },
  { path: "/es/en/terms/", lang: "en", label: "terms es-EN" },
  { path: "/lv/terms/", lang: "lv", label: "terms lv" },
  { path: "/lv/en/terms/", lang: "en", label: "terms lv-EN" },
  { path: "/is/terms/", lang: "is", label: "terms is" },
  { path: "/is/en/terms/", lang: "en", label: "terms is-EN" },
  { path: "/pt/terms/", lang: "pt", label: "terms pt" },
  { path: "/pt/en/terms/", lang: "en", label: "terms pt-EN" },
  { path: "/hu/terms/", lang: "hu", label: "terms hu" },
  { path: "/hu/en/terms/", lang: "en", label: "terms hu-EN" },
  { path: "/si/terms/", lang: "sl", label: "terms si" },
  { path: "/si/en/terms/", lang: "en", label: "terms si-EN" },
  { path: "/lt/terms/", lang: "lt", label: "terms lt" },
  { path: "/lt/en/terms/", lang: "en", label: "terms lt-EN" },
  { path: "/rs/terms/", lang: "sr", label: "terms rs" },
  { path: "/rs/en/terms/", lang: "en", label: "terms rs-EN" },
  { path: "/ie/terms/", lang: "en", label: "terms ie" },
  { path: "/sk/terms/", lang: "sk", label: "terms sk" },
  { path: "/sk/en/terms/", lang: "en", label: "terms sk-EN" },
  { path: "/ba/terms/", lang: "bs", label: "terms ba" },
  { path: "/ba/en/terms/", lang: "en", label: "terms ba-EN" },
  { path: "/ch/terms/", lang: "de", label: "terms ch" },
  { path: "/ch/en/terms/", lang: "en", label: "terms ch-EN" },
  { path: "/al/terms/", lang: "sq", label: "terms al" },
  { path: "/al/en/terms/", lang: "en", label: "terms al-EN" },
  { path: "/mk/terms/", lang: "mk", label: "terms mk" },
  { path: "/mk/en/terms/", lang: "en", label: "terms mk-EN" },
  { path: "/ro/terms/", lang: "ro", label: "terms ro" },
  { path: "/ro/en/terms/", lang: "en", label: "terms ro-EN" },
  { path: "/cy/terms/", lang: "el", label: "terms cy" },
  { path: "/cy/en/terms/", lang: "en", label: "terms cy-EN" },
  { path: "/mt/terms/", lang: "en", label: "terms mt" },
  { path: "/md/terms/", lang: "ro", label: "terms md" },
  { path: "/md/en/terms/", lang: "en", label: "terms md-EN" },
];

// EFB guide pages - every locale (single uniform slug /efb).
const efbPages: TestPage[] = [
  { path: "/uk/efb/", lang: "en", label: "efb uk" },
  { path: "/de/efb/", lang: "de", label: "efb de" },
  { path: "/de/en/efb/", lang: "en", label: "efb de-EN" },
  { path: "/fr/efb/", lang: "fr", label: "efb fr" },
  { path: "/fr/en/efb/", lang: "en", label: "efb fr-EN" },
  { path: "/nl/efb/", lang: "nl", label: "efb nl" },
  { path: "/nl/en/efb/", lang: "en", label: "efb nl-EN" },
  { path: "/at/efb/", lang: "de", label: "efb at" },
  { path: "/at/en/efb/", lang: "en", label: "efb at-EN" },
  { path: "/be/efb/", lang: "en", label: "efb be" },
  { path: "/cz/efb/", lang: "cs", label: "efb cz" },
  { path: "/cz/en/efb/", lang: "en", label: "efb cz-EN" },
  { path: "/dk/efb/", lang: "da", label: "efb dk" },
  { path: "/dk/en/efb/", lang: "en", label: "efb dk-EN" },
  { path: "/gr/efb/", lang: "el", label: "efb gr" },
  { path: "/gr/en/efb/", lang: "en", label: "efb gr-EN" },
  { path: "/no/efb/", lang: "nb", label: "efb no" },
  { path: "/no/en/efb/", lang: "en", label: "efb no-EN" },
  { path: "/pl/efb/", lang: "pl", label: "efb pl" },
  { path: "/pl/en/efb/", lang: "en", label: "efb pl-EN" },
  { path: "/se/efb/", lang: "sv", label: "efb se" },
  { path: "/se/en/efb/", lang: "en", label: "efb se-EN" },
  { path: "/ee/efb/", lang: "et", label: "efb ee" },
  { path: "/ee/en/efb/", lang: "en", label: "efb ee-EN" },
  { path: "/fi/efb/", lang: "fi", label: "efb fi" },
  { path: "/fi/en/efb/", lang: "en", label: "efb fi-EN" },
  { path: "/es/efb/", lang: "es", label: "efb es" },
  { path: "/es/en/efb/", lang: "en", label: "efb es-EN" },
  { path: "/lv/efb/", lang: "lv", label: "efb lv" },
  { path: "/lv/en/efb/", lang: "en", label: "efb lv-EN" },
  { path: "/is/efb/", lang: "is", label: "efb is" },
  { path: "/is/en/efb/", lang: "en", label: "efb is-EN" },
  { path: "/pt/efb/", lang: "pt", label: "efb pt" },
  { path: "/pt/en/efb/", lang: "en", label: "efb pt-EN" },
  { path: "/hu/efb/", lang: "hu", label: "efb hu" },
  { path: "/hu/en/efb/", lang: "en", label: "efb hu-EN" },
  { path: "/si/efb/", lang: "sl", label: "efb si" },
  { path: "/si/en/efb/", lang: "en", label: "efb si-EN" },
  { path: "/lt/efb/", lang: "lt", label: "efb lt" },
  { path: "/lt/en/efb/", lang: "en", label: "efb lt-EN" },
  { path: "/rs/efb/", lang: "sr", label: "efb rs" },
  { path: "/rs/en/efb/", lang: "en", label: "efb rs-EN" },
  { path: "/ie/efb/", lang: "en", label: "efb ie" },
  { path: "/sk/efb/", lang: "sk", label: "efb sk" },
  { path: "/sk/en/efb/", lang: "en", label: "efb sk-EN" },
  { path: "/ba/efb/", lang: "bs", label: "efb ba" },
  { path: "/ba/en/efb/", lang: "en", label: "efb ba-EN" },
  { path: "/ch/efb/", lang: "de", label: "efb ch" },
  { path: "/ch/en/efb/", lang: "en", label: "efb ch-EN" },
  { path: "/al/efb/", lang: "sq", label: "efb al" },
  { path: "/al/en/efb/", lang: "en", label: "efb al-EN" },
];

/** Root landing page (`/`) — its own <html> with a manually rendered <head>. */
export const rootPage: TestPage = { path: "/", lang: "en", label: "root" };

/** Every indexable page whose metadata must be unique and complete. */
export const allPages: TestPage[] = [
  rootPage,
  ...countryPages,
  ...airportListPages,
  ...searchPages,
  ...termsPages,
  ...efbPages,
];

/** A representative subset for the (slower) accessibility sweep. */
export const a11yPages: TestPage[] = [
  rootPage,
  { path: "/de/", lang: "de", label: "country de" },
  // A prefix != ISO-code country (at -> de): catches invalid [lang] values
  // derived from the URL prefix, which de/fr mask (Lighthouse hit on /at/).
  { path: "/at/", lang: "de", label: "country at" },
  { path: "/de/flughafen-liste-deutschland/", lang: "de", label: "list de" },
  { path: "/de/vfr/", lang: "de", label: "vfr de" },
  { path: "/fr/military/", lang: "fr", label: "military fr" },
  { path: "/de/efb/", lang: "de", label: "efb de" },
];
